import Vue from 'vue';
import 'ant-design-vue/dist/antd.css'
import { Select,Button,FormModel,Checkbox,Form,Input,Icon } from 'ant-design-vue';

Vue.use(FormModel);
Vue.use(Select);
Vue.use(Button);
Vue.use(Checkbox);
Vue.use(Select);
Vue.use(Form);
Vue.use(Input);
Vue.use(Icon);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);
// Vue.use(Select);